### ISSUE TITLE
Custom Knight grey screen thingy

### ISSUE THREAD

**Issue by osu4GBRAM** [hk-modding/modlinks#208]
After installing Custom Knight and running Hollow Knight, there's a grey screen. Please help.

**Comment by flibber-hk** [comment]
Custom Knight questions belong in the [Custom Knight repo](https://github.com/PrashantMohta/HollowKnight.CustomKnight).

Or, from the help channels of the Hollow Knight discord (search Hollow Knight discord in Google to find it)
