### ISSUE TITLE
Optional author(s) field

### ISSUE THREAD

**Issue by Spozder** [hk-modding/modlinks#764]
Hello! It would be great to be able to see who to credit for all the mods listed here, what would it take to add an optional "Authors" field that can be pulled from this list? I wouldn't expect mods to be backfilled quickly, but new/updated mods could have the authors added, and it would be great to be able to pull that into various other mod listing tools that source from this list.

Assuming this change just requires adding the field to `Schemas/ModLinks.xml`, I'd be happy to create a PR for this too! It looks like it would basically just require adding:
```xml
<xs:sequence minOccurs="0" maxOccurs="1">
  <xs:element name="Authors" type="mm:AuthorListType" />
</xs:sequence>
```

**Comment by SFGrenade** [comment]
Doesn't sound bad, only problem would be adaption in modinstallers, which can take a while

**Comment by Spozder** [comment]
Yeah assuming this went through I was planning on opening an issue/maybe a PR in [fifty-six/Scarab](https://github.com/fifty-six/Scarab) as a starting place

**Comment by Spozder** [comment]
Hi @SFGrenade I made a quick PR to add this optional Authors node - lmk what you think!
