### ISSUE TITLE
[request] i don't know where to post plugin requests :(

### ISSUE THREAD

**Issue by atesin** [hk-modding/modlinks#893]
hi ... i just want a simple mod: change the overall game speed (slower or faster)

it so frustrating to me that i find some bosses so damn fast... i dont want invincibility or 1-hit instakill... i am sure if the game would a tiny bit slower i could follow the pace without getting overwhelmed with controller hittings

.... but i don't have tools to search the mod, the ModLinks.xml file is not so friendly to do searches and a search for "speed" just gave me "speedrunning" related mods...  not what i want

is there any centralized way to request/discuss mods without contacting every developer by one?, or to add "tags" or "keywords" to mods to categorize easier? .. or maybe, an online mod/modlinks browser tool?

thanks

**Comment by HKLab** [comment]
https://discord.gg/8AqmJjEwcV
